name: 'Commit tags'
description: 'Check commit (sauce) tags in an OSS based NCS repository'
inputs:
  target:
    description: 'path to the target repository'
    default: 'none'
  baserev:
    description: 'base revision to use. Will compute a rev-list --first-parent to HEAD'
    default: 'none'
  upstream:
    description: 'Upstream <org>/<repo>/<branch>'
    default: 'none'
  github-token:
    description: 'The token to authenticate with'
  args:
    description: 'additional arguments'

runs:
  using: "composite"
  steps:
    - id: setup-python
      run: |
        pip3 install setuptools wheel
        pip3 install -r ${{ github.action_path }}/requirements.txt
      shell: bash
    - id: run-python
      run: |
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
           python3 ${{ github.action_path }}/action.py \
               --target "${{ inputs.target }}" \
               --baserev "${{ inputs.baserev }}" \
               --upstream "${{ inputs.upstream }}" \
               --pr "${{ github.repository }}/${{ github.event.pull_request.number }}" \

      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
